### ISSUE TITLE
Downloaded everything still doesnt work

### ISSUE THREAD

**Issue by itsasonnyday** [itsnewtjam/newtLib-Issues#1]
I downloaded Vault, Newtlib, and newtshop and it still doesn't work. im using 1.15.2 and it allows me to use /shop the command but doesn't do anything. Please help me im desperate. Also I could find anything called "Vault Economy" so if that's the thing im missed could you link me to that please??? Thank you!!!!!

**Comment by itsnewtjam** [comment]
'Vault Economy' refers to any economy plugin that supports Vault. Essentials Economy is an example, but most economy plugins tend to support Vault. That should be all you need to get up and running!
